#!/usr/bin/env python
# -*- coding: UTF-8 -*-

"""
@project: PyCharm
@file: app_plot.py
@author: Shengqiang Zhang
@time: 2019/8/10 02:03
@mail: sqzhang77@gmail.com
"""


import plotly.graph_objs as go
import time


# 对url地址进行简化
def url_simplification(url):
    tmp_url = url

    try:
        url = url.split('//')
        url = url[1].split('/', 1)
        url = url[0].replace("www.", "")
        return url
